### ISSUE TITLE
Update webpoll mailing templates

### ISSUE THREAD

**Issue by ferranrego** [vocdoni/vocdoni-manager-backend#1]
**Issue**
The email copies that the manager sends to the participants are outdated and only in catalan.

**Solution**
Create and update copies in catalan, castillian and english.

**Comment by emmdim** [comment]
@ferranrego The template actually being used is: 
https://github.com/vocdoni/vocdoni-manager-backend/blob/master/misc/mail/voting_template_cat.mjml
You should create the corresponding mjml templates: `voting_template_es.mjml`and `voting_template_en.mjml`
