### ISSUE TITLE
Improve error message when adding member with duplicate email

### ISSUE THREAD

**Issue by NateWilliams2** [vocdoni/vocdoni-manager-backend#26]
### Bug description
I was getting an error when importing a member with a duplicate email, and had to investigate for myself what the problem was

### Steps to reproduce

- In https://manager.dev.vocdoni.net
- Steps to reproduce the behavior:
    1. Login
    2. Go to import members
    3. Import a member from  the web ui with an email that an existing member already has

### Current behavior
Generic error message:
<img width="1180" alt="Screen Shot 2021-03-02 at 11 06 06 AM" src="https://user-images.githubusercontent.com/43301705/109686225-b1c05b00-7b47-11eb-9c45-cd3d8cad8840.png">

### Expected behavior
There should be a clear error message that says "this email is already registered to a user" or something link that :)

**Comment by emmdim** [comment]
Solved by:
Backend: 88d76df6309e930bacb1d1ec9a84475bade641c4
Frontend: 379fc7eb9662026425f87ff5af374e6f8ac7e763
