### ISSUE TITLE
Update go-dvote

### ISSUE THREAD

**Issue by emmdim** [vocdoni/vocdoni-manager-backend#7]
* [x] Install new go-dvote version
* [x] Change Message signatures to HexBytes
* [x] Update Ethereum contracts for Notif service
* [x] Change go package of backend to github
* [x] Update for new type changes: https://github.com/vocdoni/go-dvote/pull/67
   * [x] use only compressed keys.
   * [x] use ethereum address as EntityID

**Comment by emmdim** [comment]
@jordipainan  -> Could you take care of the Notif service update?
The branch https://github.com/vocdoni/vocdoni-manager-backend/tree/f/update_godvote already has the updated `go_dvote` version so you can commit to it

**Comment by jordipainan** [comment]
working on it

**Comment by emmdim** [comment]
@elboletaire This will need update on the manager-frontend:
Update EntityID to be the ethereum Address (in case you get the id from `dvote-js` no change should be needed)
